M48
; DRILL file {KiCad 9.0.3} date 2025-10-10T19:55:03+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-10T19:55:03+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C1.550
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C2.050
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C2.500
%
G90
G05
T1
X177.61Y-143.647
X183.39Y-143.647
T2
X172.75Y-135.4
T3
X168.25Y-135.4
T5
X170.25Y-135.4
T6
X164.0Y-147.0
X165.28Y-69.998
X195.76Y-69.998
X197.0Y-147.0
T4
G00X170.25Y-139.525
M15
G01X170.25Y-140.275
M16
G05
M30
